import test from "node:test";import assert from "node:assert/strict";import { webcrypto } from "node:crypto";if(!globalThis.crypto)globalThis.crypto=webcrypto;
import { blankRecipe,normalizeRecipe,validateRecipe,recipeMatches,sortRecipes,buildBackup,parseBackup,canRoleEdit } from "../src/model.js";

test("recipe normalization is bounded and predictable",()=>{const value=normalizeRecipe({...blankRecipe(),title:"  Pie  ",ingredients:"flour\n\n butter",steps:"mix\nbake",tags:"Family, Dessert, family",privacy:"invalid",prepMinutes:"12.4"});assert.equal(value.title,"Pie");assert.deepEqual(value.ingredients,["flour","butter"]);assert.deepEqual(value.tags,["family","dessert"]);assert.equal(value.privacy,"private");assert.equal(value.prepMinutes,12);});
test("recipe validation requires useful content",()=>{assert.equal(validateRecipe(normalizeRecipe({title:"",ingredients:[],steps:[]})).length,3);assert.deepEqual(validateRecipe(normalizeRecipe({title:"Soup",ingredients:["water"],steps:["boil"]})),[]);});
test("search covers lineage and respects privacy",()=>{const recipe=normalizeRecipe({title:"Noodles",ingredients:["flour"],steps:["knead"],privacy:"family",origin:{creator:"Grandma Mina",place:"Busan"}});assert.equal(recipeMatches(recipe,"mina","family"),true);assert.equal(recipeMatches(recipe,"mina","private"),false);});
test("sorting does not mutate input",()=>{const a=normalizeRecipe({title:"B",ingredients:["x"],steps:["y"]}),b=normalizeRecipe({title:"A",ingredients:["x"],steps:["y"]});const input=[a,b];const sorted=sortRecipes(input,"title");assert.equal(sorted[0].title,"A");assert.equal(input[0].title,"B");});
test("versioned backups round-trip",()=>{const recipe=normalizeRecipe({title:"Tea",ingredients:["water"],steps:["steep"]});const backup=buildBackup({recipes:[recipe],circles:[{id:"c1"}]});const restored=parseBackup(JSON.stringify(backup));assert.equal(restored.version,3);assert.equal(restored.recipes[0].title,"Tea");assert.equal(restored.circles.length,1);});
test("only contributor and custodian roles edit",()=>{assert.equal(canRoleEdit("viewer"),false);assert.equal(canRoleEdit("contributor"),true);assert.equal(canRoleEdit("custodian"),true);});
