import { INGREDIENT_LIBRARY,EQUIPMENT_LIBRARY,kitchenCategories } from "./kitchen-library.js";
import { TECHNIQUES,HEAT_LEVELS,GOALS,FLAVORS,simulateAlchemy } from "./culinary-engine.js";
import { enhanceWithLocalAI,getLocalAICapabilities } from "./local-ai.js";
import { GENERATED_IMAGES as IMG } from "./generated-images.js";
const TRIAL_KEY="mangrok.alchemy.trials.v1",SETTINGS_KEY="mangrok.alchemy.settings.v1";
const state={mode:"ingredients",category:"All",query:"",ingredients:new Set(["Chicken","Garlic","Lemon","Tomato","Olive oil","Basil"]),equipment:new Set(["Cast-iron skillet","Tongs"]),technique:"sear",heat:"medium-high",time:18,servings:2,goal:"balanced",provider:"rules",busy:false,result:null,settings:loadSettings()};
ready(init);
function ready(fn){document.readyState==="loading"?document.addEventListener("DOMContentLoaded",fn,{once:true}):fn()}
function init(){addNav();addView();bindStandardNav();renderAll();if(location.hash==="#alchemy")setTimeout(open,100)}
function addNav(){const d=document.querySelector(".nav-list");if(d&&!d.querySelector("[data-alchemy-nav]")){const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.alchemyNav="";b.textContent="Alchemy Lab";d.querySelector('[data-view="circles"]')?.insertAdjacentElement("beforebegin",b)}const m=document.querySelector(".mobile-nav");if(m&&!m.querySelector("[data-alchemy-mobile]")){const b=document.createElement("button");b.type="button";b.dataset.alchemyMobile="";b.textContent="Alchemy";m.querySelector('[data-view="circles"]')?.insertAdjacentElement("beforebegin",b)}document.querySelectorAll("[data-alchemy-nav],[data-alchemy-mobile]").forEach(button=>{button.onclick=open})}
function addView(){const main=document.querySelector("#main");if(!main||document.querySelector("#view-alchemy"))return;const s=document.createElement("section");s.id="view-alchemy";s.className="view alchemy-view";s.dataset.viewPanel="alchemy";s.innerHTML=`
<section class="alchemy-hero"><img src="${IMG.hero}" alt="A generated cinematic cooking laboratory"><div><p class="eyebrow">Mangrok culinary discovery engine</p><h2>Build a dish as a living formula.</h2><p>Combine ingredients, cookware, heat, time, and technique. Mangrok predicts balance, risk, and evolution, then an optional local model can refine the assessment.</p><div id="alchemy-trials"></div></div></section>
<section class="alchemy-grid">
<article class="panel alchemy-library"><header><div><p class="eyebrow">Elements</p><h3>Kitchen library</h3></div><b id="alchemy-count"></b></header><div class="alchemy-tabs"><button data-mode="ingredients">Ingredients</button><button data-mode="equipment">Equipment</button></div><div class="alchemy-search"><input id="alchemy-search" type="search" placeholder="Search ingredients or equipment"><select id="alchemy-category"></select></div><div id="alchemy-cards" class="alchemy-cards"></div><div class="alchemy-custom"><input id="alchemy-custom" maxlength="80" placeholder="Custom family element"><button class="mini-button" id="alchemy-add" type="button">Add item</button></div></article>
<article class="panel alchemy-formula"><header><p class="eyebrow">Formula</p><h3>Active experiment</h3></header><h4>Ingredients</h4><div class="alchemy-selected" id="alchemy-selected-ingredients"></div><h4>Equipment</h4><div class="alchemy-selected" id="alchemy-selected-equipment"></div><div class="alchemy-controls"><label>Technique<select id="alchemy-technique">${TECHNIQUES.map(v=>`<option value="${v.id}">${v.label}</option>`).join("")}</select></label><label>Heat<select id="alchemy-heat">${HEAT_LEVELS.map(v=>`<option value="${v.id}">${v.label}</option>`).join("")}</select></label><label>Minutes<input id="alchemy-time" type="number" min="1" max="360" value="18"></label><label>Servings<input id="alchemy-servings" type="number" min="1" max="24" value="2"></label><label class="wide">Direction<select id="alchemy-goal">${GOALS.map(v=>`<option value="${v.id}">${v.label}</option>`).join("")}</select></label></div><section class="alchemy-provider"><p class="eyebrow">Reasoning mode</p><div id="alchemy-providers"></div><details><summary>Self-hosted model settings</summary><label>Endpoint<input id="alchemy-endpoint" value="${esc(state.settings.url)}"></label><label>Model<input id="alchemy-model" value="${esc(state.settings.model)}"></label><button class="mini-button" id="alchemy-save-settings" type="button">Save local settings</button></details><div id="alchemy-progress" hidden><i><b></b></i><p></p></div></section><div class="button-row"><button class="button primary" id="alchemy-run" type="button">Run Alchemy</button><button class="button ghost" id="alchemy-reset" type="button">Reset</button></div><p class="alchemy-note">Prediction, not a physical guarantee. Verify allergens and food-safety requirements independently.</p></article></section>
<section class="panel alchemy-preview"><div><p class="eyebrow">Live preview</p><h3>Formula balance updates as you work.</h3><p id="alchemy-preview-copy"></p></div><div id="alchemy-preview-metrics"></div></section><section id="alchemy-results" class="alchemy-results" hidden></section>`;main.prepend(s);bind(s)}
function bind(root){root.querySelector(".alchemy-tabs").onclick=e=>{const b=e.target.closest("[data-mode]");if(!b)return;state.mode=b.dataset.mode;state.category="All";state.query="";root.querySelector("#alchemy-search").value="";renderLibrary()};root.querySelector("#alchemy-search").oninput=e=>{state.query=e.target.value;renderLibrary()};root.querySelector("#alchemy-category").onchange=e=>{state.category=e.target.value;renderLibrary()};root.querySelector("#alchemy-cards").onclick=e=>{const b=e.target.closest("[data-item]");if(b)toggle(b.dataset.item)};root.querySelector("#alchemy-selected-ingredients").onclick=remove;root.querySelector("#alchemy-selected-equipment").onclick=remove;root.querySelector("#alchemy-add").onclick=addCustom;root.querySelector("#alchemy-custom").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addCustom()}};for(const [id,key]of [["alchemy-technique","technique"],["alchemy-heat","heat"],["alchemy-time","time"],["alchemy-servings","servings"],["alchemy-goal","goal"]])root.querySelector(`#${id}`).oninput=e=>{state[key]=["time","servings"].includes(key)?Number(e.target.value):e.target.value;if(key==="technique"){state.heat=TECHNIQUES.find(v=>v.id===state.technique)?.heat||state.heat;root.querySelector("#alchemy-heat").value=state.heat}preview()};root.querySelector("#alchemy-providers").onchange=e=>{if(e.target.name==="alchemy-provider")state.provider=e.target.value};root.querySelector("#alchemy-run").onclick=run;root.querySelector("#alchemy-reset").onclick=reset;root.querySelector("#alchemy-save-settings").onclick=saveSettings;root.querySelector("#alchemy-results").onclick=e=>{if(e.target.closest("#alchemy-vault"))saveToVault();if(e.target.closest("#alchemy-export"))exportResult()}}
function bindStandardNav(){document.addEventListener("click",e=>{if(e.target.closest("[data-view]"))document.querySelectorAll("[data-alchemy-nav],[data-alchemy-mobile]").forEach(x=>x.classList.remove("active"))});window.addEventListener("hashchange",()=>{if(location.hash==="#alchemy")open()})}
function open(){const p=document.querySelector("#view-alchemy");if(!p)return;document.querySelectorAll("[data-view-panel]").forEach(x=>x.classList.toggle("active",x===p));document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));document.querySelectorAll("[data-alchemy-nav],[data-alchemy-mobile]").forEach(x=>x.classList.add("active"));document.querySelector("#view-eyebrow").textContent="AI cooking laboratory";document.querySelector("#view-title").textContent="Alchemy Lab";document.querySelector("#new-recipe-button").hidden=true;if(location.hash!=="#alchemy")history.replaceState(null,"","#alchemy")}
function renderAll(){const r=document.querySelector("#view-alchemy");if(!r)return;r.querySelector("#alchemy-technique").value=state.technique;r.querySelector("#alchemy-heat").value=state.heat;r.querySelector("#alchemy-goal").value=state.goal;renderLibrary();renderSelected();renderProviders();renderTrials();preview()}
function renderLibrary(){const root=document.querySelector("#view-alchemy");if(!root)return;const src=state.mode==="equipment"?EQUIPMENT_LIBRARY:INGREDIENT_LIBRARY,sel=state.mode==="equipment"?state.equipment:state.ingredients,q=state.query.trim().toLowerCase(),cats=kitchenCategories(state.mode);root.querySelector("#alchemy-category").innerHTML=cats.map(v=>`<option${v===state.category?" selected":""}>${html(v)}</option>`).join("");root.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.mode));const image=state.mode==="equipment"?IMG.equipment:IMG.ingredients;root.querySelector("#alchemy-cards").innerHTML=src.filter(x=>(state.category==="All"||x.category===state.category)&&(!q||`${x.name} ${x.category}`.toLowerCase().includes(q))).slice(0,42).map((x,i)=>`<button type="button" data-item="${esc(x.name)}" class="alchemy-card ${sel.has(x.name)?"selected":""}"><img src="${image}" alt="" style="object-position:${(i%7)*14}% ${(Math.floor(i/7)%5)*25}%"><span><b>${html(x.name)}</b><small>${html(x.category)}</small></span><em>${sel.has(x.name)?"Selected":"Add"}</em></button>`).join("");root.querySelector("#alchemy-count").textContent=`${sel.size} selected`}
function renderSelected(){list("#alchemy-selected-ingredients",state.ingredients,"ingredients");list("#alchemy-selected-equipment",state.equipment,"equipment")}
function list(id,set,mode){const r=document.querySelector(id);r.innerHTML=set.size?[...set].map(v=>`<span>${html(v)}<button data-remove="${esc(v)}" data-remove-mode="${mode}" type="button">Remove</button></span>`).join(""):`<p>No ${mode} selected.</p>`}
function renderProviders(){const c=getLocalAICapabilities(config()),r=document.querySelector("#alchemy-providers"),rows=[{id:"rules",n:"Instant culinary engine",d:"Explainable flavor, technique, timing, and risk rules."},{id:"webllm",n:"On-device local LLM",d:c.webgpu?`Runs ${c.webllmModel} in this browser after a model download.`:"WebGPU is unavailable in this browser.",off:!c.webgpu},{id:"ollama",n:"Self-hosted model",d:"Use your own OpenAI-compatible local endpoint."},...(c.gateway?[{id:"gateway",n:"Mangrok private gateway",d:"Use the configured authenticated subscriber endpoint."}]:[])];if(!rows.some(x=>x.id===state.provider&&!x.off))state.provider="rules";r.innerHTML=rows.map(x=>`<label class="${x.off?"disabled":""}"><input type="radio" name="alchemy-provider" value="${x.id}" ${state.provider===x.id?"checked":""} ${x.off?"disabled":""}><span><b>${x.n}</b><small>${x.d}</small></span></label>`).join("")}
function renderTrials(){const limit=Number(window.MANGROK_CONFIG?.alchemyTrialLimit)||10,used=Number(localStorage.getItem(TRIAL_KEY))||0,left=Math.max(0,limit-used),r=document.querySelector("#alchemy-trials"),b=document.querySelector("#alchemy-run");r.innerHTML=`<b>${left} of ${limit} discovery runs remaining</b><span>Live previews do not use a trial.</span>`;b.disabled=left<=0||state.busy;b.textContent=left<=0?"Trial complete — subscription required":state.busy?"Running Alchemy…":"Run Alchemy"}
function preview(){if(state.ingredients.size<2){document.querySelector("#alchemy-preview-copy").textContent="Select at least two ingredients to begin.";document.querySelector("#alchemy-preview-metrics").innerHTML="";return}const v=simulateAlchemy(input());document.querySelector("#alchemy-preview-copy").textContent=v.summary;document.querySelector("#alchemy-preview-metrics").innerHTML=[["Direction",v.outcome],["Confidence",`${v.confidence}%`],["Equipment fit",`${v.equipmentFit.score}%`],["Leading flavor",top(v.flavor)]].map(([a,b])=>`<div><small>${a}</small><b>${b}</b></div>`).join("")}
async function run(){if(state.busy||state.ingredients.size<2)return;const limit=Number(window.MANGROK_CONFIG?.alchemyTrialLimit)||10,used=Number(localStorage.getItem(TRIAL_KEY))||0;if(used>=limit)return;state.busy=true;renderTrials();progress("Building the culinary assessment.",8);const base=simulateAlchemy(input());try{const out=await enhanceWithLocalAI({input:base.input,simulation:base,provider:state.provider,config:config(),onProgress:p=>progress(p.text||"Preparing local AI.",p.progress)});state.result={...out.result,providerLabel:out.model}}catch(e){state.result={...base,providerLabel:"Mangrok culinary engine",fallback:e.message};progress(`Local AI failed; the explainable result was preserved. ${e.message}`,100,true)}localStorage.setItem(TRIAL_KEY,String(used+1));state.busy=false;renderTrials();result()}
function result(){const v=state.result,r=document.querySelector("#alchemy-results");r.hidden=false;r.innerHTML=`<article class="panel alchemy-outcome"><img src="${IMG.insights}" alt="A generated plated-dish insight scene"><div><p class="eyebrow">${v.outcome}</p><h2>${html(v.title)}</h2><p>${html(v.summary)}</p><strong>${v.confidence}% prediction confidence</strong><small>Reasoning source: ${html(v.providerLabel)}</small><div class="button-row"><button class="button primary" id="alchemy-vault">Save to Vault</button><button class="button ghost" id="alchemy-export">Export experiment</button></div></div></article><div class="alchemy-result-grid"><section class="panel"><p class="eyebrow">Flavor balance</p><h3>Predicted profile</h3>${FLAVORS.map(k=>`<div class="flavor"><span>${k}</span><i><b style="width:${v.flavor[k]}%"></b></i><strong>${v.flavor[k]}</strong></div>`).join("")}</section><section class="panel"><p class="eyebrow">Risk review</p><h3>What could go wrong</h3>${v.risks.length?v.risks.map(x=>`<article class="risk ${x.severity}"><b>${html(x.message)}</b><p>${html(x.action)}</p></article>`).join(""):"<p>No major contradiction was detected.</p>"}</section><section class="panel"><p class="eyebrow">Chef notes</p><h3>Ways to improve it</h3><ul>${[...(v.aiInsights||[]),...v.suggestions].slice(0,8).map(x=>`<li>${html(x)}</li>`).join("")}</ul></section><section class="panel"><p class="eyebrow">Culinary science</p><h3>Why it behaves this way</h3><ul>${v.science.map(x=>`<li>${html(x)}</li>`).join("")}</ul></section></div><section class="panel alchemy-timeline"><p class="eyebrow">Cooking timeline</p><h3>Predicted evolution</h3><div>${v.stages.map((x,i)=>`<article><small>Stage ${i+1}</small><h4>${html(x.name)}</h4><b>${x.minutes} min</b><p>${html(x.cue)}</p></article>`).join("")}</div></section><section class="alchemy-evolutions"><img src="${IMG.evolution}" alt="A generated recipe evolution scene"><div>${v.evolutions.map(x=>`<article class="panel"><h3>${html(x.name)}</h3><p>${html(x.change)}</p><small>${html(x.reason)}</small></article>`).join("")}</div></section><p class="alchemy-disclaimer">${html(v.disclaimer)}</p>`;r.scrollIntoView({behavior:"smooth",block:"start"})}
function toggle(name){const s=state.mode==="equipment"?state.equipment:state.ingredients;s.has(name)?s.delete(name):s.add(name);renderLibrary();renderSelected();preview()}
function remove(e){const b=e.target.closest("[data-remove]");if(!b)return;(b.dataset.removeMode==="equipment"?state.equipment:state.ingredients).delete(b.dataset.remove);renderLibrary();renderSelected();preview()}
function addCustom(){const i=document.querySelector("#alchemy-custom"),v=i.value.trim().replaceAll(","," ").slice(0,80);if(!v)return;(state.mode==="equipment"?state.equipment:state.ingredients).add(v);i.value="";renderLibrary();renderSelected();preview()}
function reset(){state.ingredients=new Set(["Chicken","Garlic","Lemon","Tomato","Olive oil","Basil"]);state.equipment=new Set(["Cast-iron skillet","Tongs"]);state.technique="sear";state.heat="medium-high";state.time=18;state.servings=2;state.goal="balanced";document.querySelector("#alchemy-results").hidden=true;renderAll()}
function saveSettings(){state.settings={url:document.querySelector("#alchemy-endpoint").value.trim(),model:document.querySelector("#alchemy-model").value.trim()};localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));progress("Local model settings saved on this device.",100)}
function saveToVault(){const v=state.result;document.querySelector("#new-recipe-button")?.click();const fill=()=>{const d=document.querySelector("#recipe-dialog"),f=document.querySelector("#recipe-form");if(!d?.open||!f)return setTimeout(fill,40);f.elements.title.value=v.title;f.elements.summary.value=`${v.summary}\n\nAlchemy confidence: ${v.confidence}%.`;f.elements.servings.value=v.input.servings;f.elements.cookMinutes.value=v.input.timeMinutes;f.elements.ingredients.value=v.input.ingredients.join("\n");f.elements.steps.value=v.stages.map(x=>`${x.name} (${x.minutes} min): ${x.cue}`).join("\n");f.elements.tags.value=`alchemy, ai-discovered, ${v.input.goal}`;f.elements.story.value=`Created in Mangrok Alchemy.\n\n${v.science.map(x=>`- ${x}`).join("\n")}`;window.dispatchEvent(new CustomEvent("mangrok:kitchen-selection",{detail:{ingredients:v.input.ingredients,equipment:v.input.equipment}}))};fill()}
function exportResult(){const b=new Blob([JSON.stringify({type:"mangrok.alchemy",version:1,experiment:state.result},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="mangrok-alchemy-experiment.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function progress(text,p=40,error=false){const r=document.querySelector("#alchemy-progress");r.hidden=false;r.classList.toggle("error",error);r.querySelector("p").textContent=text;r.querySelector("b").style.width=`${Number.isFinite(Number(p))?Math.max(3,Math.min(100,p)):40}%`}
function input(){return{ingredients:[...state.ingredients],equipment:[...state.equipment],technique:state.technique,heat:state.heat,timeMinutes:state.time,servings:state.servings,goal:state.goal}}
function config(){return{...(window.MANGROK_CONFIG||{}),ollamaBaseUrl:state.settings.url,ollamaModel:state.settings.model}}
function loadSettings(){try{const v=JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}");return{url:String(v.url||"http://127.0.0.1:11434/v1"),model:String(v.model||"llama3.2")}}catch{return{url:"http://127.0.0.1:11434/v1",model:"llama3.2"}}}
function top(f){return FLAVORS.toSorted((a,b)=>f[b]-f[a])[0]}
function html(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}function esc(v){return html(v).replaceAll("`","&#96;")}
