export const TECHNIQUES = Object.freeze([
  ["sear","Sear","medium-high","Frying pan|Cast-iron skillet|Sauté pan"],
  ["saute","Sauté","medium","Frying pan|Sauté pan|Wok"],
  ["simmer","Simmer","medium-low","Saucepan|Stockpot|Dutch oven"],
  ["roast","Roast","medium-high","Oven|Baking sheet|Dutch oven"],
  ["bake","Bake","medium","Oven|Cake pan|Baking sheet"],
  ["grill","Grill","high","Griddle|Grill pan|Oven"],
  ["steam","Steam","medium","Steamer basket|Stockpot|Saucepan"],
  ["braise","Braise","low","Dutch oven|Stockpot|Slow cooker"],
  ["fry","Fry","medium-high","Frying pan|Wok|Dutch oven"],
  ["mix","Mix / assemble","off","Mixing bowl|Chef knife|Cutting board"]
].map(([id,label,heat,equipment])=>({id,label,heat,equipment:equipment.split("|")})));
export const HEAT_LEVELS = Object.freeze([["off","No heat",0],["low","Low",.25],["medium-low","Medium-low",.4],["medium","Medium",.55],["medium-high","Medium-high",.75],["high","High",.92]].map(([id,label,value])=>({id,label,value})));
export const GOALS = Object.freeze([["balanced","Balanced"],["comforting","Comforting"],["healthy","Lighter"],["quick","Quick"],["spicy","Spicy"],["gourmet","Gourmet"],["festive","Festive"]].map(([id,label])=>({id,label})));
export const FLAVORS = Object.freeze(["sweet","salty","acidic","bitter","umami","heat","richness"]);

export function simulateAlchemy(raw={}){
  const input=normalizeInput(raw), profiles=input.ingredients.map(profileIngredient), technique=TECHNIQUES.find(v=>v.id===input.technique)||TECHNIQUES[0], heat=HEAT_LEVELS.find(v=>v.id===input.heat)||HEAT_LEVELS[3];
  const flavor=Object.fromEntries(FLAVORS.map(key=>[key,Math.round(Math.min(1,profiles.reduce((s,p)=>s+p[key],0)/Math.max(1,Math.sqrt(profiles.length)))*100)]));
  const equipmentFit=scoreEquipment(input.equipment,technique), risks=evaluateRisks(input,profiles,technique,heat,flavor,equipmentFit), suggestions=buildSuggestions(profiles,flavor,technique,equipmentFit,risks);
  const confidence=clamp(62+Math.min(16,profiles.length*2)+Math.round((equipmentFit.score-50)*.15)-risks.reduce((n,r)=>n+(r.severity==="high"?10:r.severity==="medium"?5:2),0),18,96);
  const primary=profiles.find(p=>p.protein>.5)||profiles.find(p=>p.category==="Vegetables")||profiles[0]||{name:"Kitchen experiment"};
  const aromatic=profiles.find(p=>p.aromatic>.6&&p!==primary);
  const title=[technique.label,aromatic?.name,primary.name].filter(Boolean).join(" ");
  const stages=buildStages(input,profiles,technique,heat);
  return Object.freeze({version:1,generatedAt:new Date().toISOString(),input,title,summary:`A ${input.goal} ${technique.label.toLowerCase()} direction led by ${input.ingredients.slice(0,3).join(", ")}, with ${topFlavors(flavor).join(" and ")} as the strongest predicted notes.`,confidence,flavor,equipmentFit,risks,suggestions,stages,science:scienceNotes(profiles,technique,heat),evolutions:evolutions(primary.name,technique),outcome:confidence>=82?"Strong direction":confidence>=65?"Promising experiment":"Needs refinement",disclaimer:"AI-guided culinary prediction only. Actual results depend on ingredient size, equipment, appliance calibration, and independent food-safety verification."});
}

export function normalizeInput(raw={}){const technique=TECHNIQUES.some(v=>v.id===raw.technique)?raw.technique:"sear";return{ingredients:unique(raw.ingredients).slice(0,30),equipment:unique(raw.equipment).slice(0,12),technique,heat:HEAT_LEVELS.some(v=>v.id===raw.heat)?raw.heat:(TECHNIQUES.find(v=>v.id===technique)?.heat||"medium"),goal:GOALS.some(v=>v.id===raw.goal)?raw.goal:"balanced",timeMinutes:clamp(Math.round(Number(raw.timeMinutes)||20),1,360),servings:clamp(Math.round(Number(raw.servings)||2),1,24),notes:String(raw.notes||"").trim().slice(0,1200)}};

export function profileIngredient(value){const name=String(value||"").trim(),s=name.toLowerCase(),p={name,category:category(s),sweet:.02,salty:.02,acidic:.02,bitter:.02,umami:.02,heat:.02,richness:.02,moisture:.35,protein:0,starch:0,rawRisk:0,delicate:.2,aromatic:0};
  add(p,s,/sugar|honey|maple|fruit|apple|pear|mango|banana|carrot|corn|pumpkin/,{sweet:.62});add(p,s,/salt|soy|fish sauce|parmesan|feta|olive|capers|stock/,{salty:.7,umami:.25});add(p,s,/lemon|lime|vinegar|tomato|yogurt|tamarind/,{acidic:.66,moisture:.2});add(p,s,/kale|broccoli|coffee|cocoa|radicchio/,{bitter:.48});add(p,s,/mushroom|tomato|soy|parmesan|stock|beef|lamb|pork|chicken|fish|shrimp|miso/,{umami:.72});add(p,s,/chili|hot sauce|pepper|paprika|ginger|mustard|harissa|cayenne/,{heat:.72});add(p,s,/butter|ghee|cream|cheese|oil|coconut milk|avocado|tahini|peanut|almond|walnut/,{richness:.78});add(p,s,/rice|pasta|noodle|flour|bread|potato|cornstarch|oat|barley|quinoa|couscous/,{starch:.9,moisture:-.15});add(p,s,/chicken|turkey|pork|beef|lamb|fish|shrimp|crab|lobster|mussel|egg/,{protein:.9,rawRisk:.82,umami:.25});add(p,s,/tofu|lentil|chickpea|bean|tempeh/,{protein:.58,umami:.18,starch:.2});add(p,s,/basil|coriander|parsley|mint|rosemary|thyme|oregano|sage|dill|saffron|vanilla|garlic|onion/,{aromatic:.9,delicate:.25});
  for(const k of Object.keys(p))if(typeof p[k]==="number")p[k]=clamp(p[k],0,1);return p}

export function buildAlchemyPrompt(input,result){return[{role:"system",content:"You are Mangrok Alchemy, a cautious culinary development assistant. Return one JSON object only. Do not claim a guaranteed physical simulation. Preserve food-safety uncertainty. Keys: title, summary, insights, risks, suggestions, stages, evolutions, confidenceAdjustment."},{role:"user",content:JSON.stringify({input,deterministicAssessment:result})}]}
export function mergeAIInsight(base,ai){if(!ai||typeof ai!=="object")return base;const adj=clamp(Math.round(Number(ai.confidenceAdjustment)||0),-10,10);return Object.freeze({...base,title:clean(ai.title,140)||base.title,summary:clean(ai.summary,900)||base.summary,confidence:clamp(base.confidence+adj,1,99),aiInsights:cleanArray(ai.insights,8,220),risks:mergeRisks(base.risks,ai.risks),suggestions:unique([...base.suggestions,...cleanArray(ai.suggestions,8,240)]).slice(0,10),stages:Array.isArray(ai.stages)&&ai.stages.length?ai.stages.slice(0,8).map(x=>({name:clean(x.name,80),minutes:clamp(Math.round(Number(x.minutes)||1),1,360),cue:clean(x.cue,260)})).filter(x=>x.name&&x.cue):base.stages,evolutions:Array.isArray(ai.evolutions)&&ai.evolutions.length?ai.evolutions.slice(0,6).map(x=>({name:clean(x.name,60),change:clean(x.change,280),reason:clean(x.reason,240)})).filter(x=>x.name&&x.change):base.evolutions,aiEnhanced:true})}

function scoreEquipment(equipment,technique){const names=equipment.map(v=>v.toLowerCase()),matches=technique.equipment.filter(v=>names.some(n=>n.includes(v.toLowerCase())||v.toLowerCase().includes(n)));return{score:equipment.length?(matches.length?96:58):45,matches,ideal:technique.equipment,message:matches.length?`${matches[0]} suits this method.`:`Consider ${technique.equipment.slice(0,2).join(" or ")} for this technique.`}}
function evaluateRisks(input,p,t,h,f,e){const out=[],fat=p.some(x=>x.richness>.62||/oil|butter|ghee/i.test(x.name)),liquid=p.some(x=>/stock|water|milk|cream|sauce|wine|juice|broth|coconut milk|canned tomatoes/i.test(x.name)),dairy=p.some(x=>/milk|cream|yogurt|cheese/i.test(x.name)),acid=p.some(x=>x.acidic>.55),raw=Math.max(0,...p.map(x=>x.rawRisk)),delicate=Math.max(0,...p.map(x=>x.delicate));
  if(["sear","saute","fry"].includes(t.id)&&h.value>=.65&&!fat)out.push(risk("medium","High-contact heat has no obvious cooking fat.","Preheat the vessel and add an appropriate fat."));if(raw>.7&&input.timeMinutes<10)out.push(risk("high","The proposed time may be too short for a raw animal protein.","Verify doneness with authoritative temperature guidance and a food thermometer."));if(raw>.7&&h.value<=.25&&!['braise','simmer'].includes(t.id))out.push(risk("high","Low dry heat creates an undercooking risk.","Increase heat or use a longer controlled method."));if(delicate>.65&&h.value>=.9)out.push(risk("medium","Delicate elements may burn before the main ingredient is ready.","Add them later or lower the heat."));if(dairy&&acid&&h.value>=.75)out.push(risk("medium","Acidic dairy mixtures can split over strong heat.","Lower heat and add acid gradually."));if(["simmer","braise"].includes(t.id)&&!liquid)out.push(risk("medium","A moist-heat technique has no obvious cooking liquid.","Add a compatible stock, water, tomato, wine, or milk-based liquid."));if(f.sweet>55&&h.value>=.75)out.push(risk("medium","Sugars may burn quickly at this heat.","Monitor color closely and reduce heat after browning begins."));if(e.score<60)out.push(risk("low","The selected equipment is not an obvious method match.",e.message));return out.slice(0,6)}
function buildSuggestions(p,f,t,e,r){const a=[];if(f.acidic<25&&f.richness>45)a.push("Add a small acidic finish to lift the richness.");if(f.salty<18)a.push("Season in stages and taste before the final adjustment.");if(f.umami<24)a.push("Consider mushroom, tomato, aged cheese, soy, or stock for savory depth.");if(!p.some(x=>x.aromatic>.5))a.push("Add an aromatic layer such as garlic, onion, ginger, or herbs.");if(p.some(x=>x.protein>.7)&&["sear","grill","roast"].includes(t.id))a.push("Rest the cooked protein before slicing.");if(e.score<90)a.push(e.message);if(!r.length)a.push("The current method is coherent; refine by tasting rather than adding more elements automatically.");return unique(a).slice(0,7)}
function buildStages(i,p,t,h){const total=i.timeMinutes,prep=Math.max(2,Math.round(total*.2)),base=t.id==="mix"?0:Math.max(2,Math.round(total*.2)),finish=Math.max(1,Math.round(total*.12)),main=Math.max(1,total-prep-base-finish),delicate=p.filter(x=>x.delicate>.6).map(x=>x.name).slice(0,3);return[{name:"Prepare",minutes:prep,cue:"Cut consistently and dry surfaces intended for browning."},...(base?[{name:"Build the base",minutes:base,cue:`Use ${h.label.toLowerCase()} heat to wake aromatics without burning them.`}]:[]),{name:t.label,minutes:main,cue:"Cook toward the intended color and texture; verify doneness rather than relying on time alone."},{name:"Finish and taste",minutes:finish,cue:delicate.length?`Add ${delicate.join(", ")} late, then adjust salt and acid.`:"Adjust salt, acid, and texture; rest if appropriate."}]}
function scienceNotes(p,t,h){const a=[],protein=p.some(x=>x.protein>.55),starch=p.some(x=>x.starch>.55),fat=p.some(x=>x.richness>.55),acid=p.some(x=>x.acidic>.55);if(h.value>=.7&&(protein||starch))a.push("Browning reactions can build roasted aroma when the surface is dry enough.");if(fat&&acid)a.push("A stable emulsion needs gradual mixing and enough water phase; excessive heat can break it.");if(starch&&["simmer","bake","braise"].includes(t.id))a.push("Starch gelatinization can thicken the mixture as granules absorb hot liquid.");if(["braise","simmer"].includes(t.id)&&protein)a.push("Long moist cooking can soften connective tissue, while lean proteins may still dry if held too long.");return a.length?a:["The main variables are heat transfer, ingredient size, moisture loss, and order of addition."]}
function evolutions(primary,t){return[{name:"Lighter",change:"Reduce heavy fat, increase vegetables, and finish with acid.",reason:"Preserves intensity while lowering perceived richness."},{name:"Faster",change:`Cut ${primary} smaller and use a high-surface-area ${t.id==="roast"?"sheet-pan":"stovetop"} method.`,reason:"More exposed surface shortens cooking time."},{name:"Spicier",change:"Bloom chili in fat, then balance with acid or a cooling garnish.",reason:"Disperses heat while protecting flavor balance."},{name:"Gourmet",change:"Develop fond, deglaze, reduce, and finish with herbs or a textured garnish.",reason:"Adds layered aroma and a deliberate finish."}]}
function mergeRisks(base,ai){const extras=Array.isArray(ai)?ai.map(x=>risk(["low","medium","high"].includes(x?.severity)?x.severity:"low",clean(x?.message,260),clean(x?.action,260))).filter(x=>x.message):[];return [...new Map([...base,...extras].map(x=>[x.message.toLowerCase(),x])).values()].slice(0,8)}
function topFlavors(f){return FLAVORS.toSorted((a,b)=>f[b]-f[a]).slice(0,2).map(v=>v==="acidic"?"bright":v)}
function category(s){if(/fruit|apple|pear|berry|mango|banana|lemon|lime|orange/.test(s))return"Fruit";if(/chicken|beef|pork|fish|shrimp|egg|tofu|bean|lentil/.test(s))return"Proteins";if(/rice|pasta|flour|bread|oat|potato/.test(s))return"Grains & pasta";if(/butter|milk|cream|cheese|yogurt/.test(s))return"Dairy & alternatives";if(/basil|thyme|pepper|paprika|garlic|onion|ginger|spice|herb/.test(s))return"Herbs & spices";return"Vegetables"}
function add(p,s,re,v){if(!re.test(s))return;for(const[k,n]of Object.entries(v))p[k]=(p[k]||0)+n}
function risk(severity,message,action){return{severity,message,action}}
function unique(v){return[...new Set((v||[]).map(x=>String(x||"").trim()).filter(Boolean))]}
function clean(v,n){return String(v||"").trim().slice(0,n)}
function cleanArray(v,max,n){return Array.isArray(v)?unique(v.map(x=>clean(x,n))).slice(0,max):[]}
function clamp(v,min,max){return Math.min(max,Math.max(min,Number(v)||0))}
