import { buildAlchemyPrompt, mergeAIInsight } from "./culinary-engine.js";
export const DEFAULT_WEBLLM_MODEL="Llama-3.2-1B-Instruct-q4f16_1-MLC";
let enginePromise=null,loadedModel="";
export function getLocalAICapabilities(config=globalThis.window?.MANGROK_CONFIG||{}){return{rules:true,webgpu:Boolean(globalThis.navigator?.gpu),webllmModel:String(config.webllmModel||DEFAULT_WEBLLM_MODEL),gateway:Boolean(String(config.aiGatewayUrl||"").trim())}}
export async function enhanceWithLocalAI({input,simulation,provider="rules",config=globalThis.window?.MANGROK_CONFIG||{},onProgress=()=>{}}){if(provider==="rules")return{result:simulation,provider,model:"Mangrok culinary engine"};const messages=buildAlchemyPrompt(input,simulation);let text,model;
  if(provider==="webllm"){model=String(config.webllmModel||DEFAULT_WEBLLM_MODEL);text=await runWebLLM(messages,model,onProgress)}
  else{const local=provider==="ollama";model=String(local?(config.ollamaModel||"llama3.2"):(config.aiGatewayModel||"local-model"));text=await runOpenAICompatible({baseUrl:local?(config.ollamaBaseUrl||"http://127.0.0.1:11434/v1"):config.aiGatewayUrl,model,messages,authorization:local?"":await requestToken()})}
  return{result:mergeAIInsight(simulation,parseStructuredResponse(text)),provider,model}}
async function runWebLLM(messages,model,onProgress){if(!navigator?.gpu)throw new Error("On-device AI requires WebGPU.");if(!enginePromise||loadedModel!==model){loadedModel=model;enginePromise=import("https://esm.run/@mlc-ai/web-llm").then(webllm=>webllm.CreateMLCEngine(model,{initProgressCallback:p=>onProgress({progress:Number.isFinite(Number(p?.progress))?Math.round(Number(p.progress)*100):null,text:String(p?.text||"Preparing local model.")})})).catch(e=>{enginePromise=null;loadedModel="";throw e})}const engine=await enginePromise;onProgress({text:"The local model is refining the recipe."});const value=await engine.chat.completions.create({messages,temperature:.25,max_tokens:1000,response_format:{type:"json_object"},stream:false});return value?.choices?.[0]?.message?.content||""}
export async function runOpenAICompatible({baseUrl,model,messages,authorization=""}){const raw=String(baseUrl||"").trim();if(!raw)throw new Error("No local AI endpoint is configured.");const base=raw.replace(/\/+$/,"");const endpoint=/\/chat\/completions$/i.test(base)?base:/\/v1$/i.test(base)?`${base}/chat/completions`:`${base}/v1/chat/completions`;const response=await fetch(endpoint,{method:"POST",mode:"cors",headers:{"Content-Type":"application/json",...(authorization?{Authorization:`Bearer ${authorization}`}:{})},body:JSON.stringify({model,messages,temperature:.25,max_tokens:1000,response_format:{type:"json_object"},stream:false})});if(!response.ok)throw new Error(`Local AI endpoint returned ${response.status}.`);const payload=await response.json(),completion=payload?.completion||payload;return completion?.choices?.[0]?.message?.content||completion?.response||completion?.output_text||""}
export function parseStructuredResponse(value){if(value&&typeof value==="object")return value;const text=String(value||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"").trim();try{return JSON.parse(text)}catch{}const a=text.indexOf("{"),b=text.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(text.slice(a,b+1))}catch{}throw new Error("The local model did not return valid structured JSON.")}
async function requestToken(){if(!globalThis.window)return"";return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;resolve(String(v||""))};window.dispatchEvent(new CustomEvent("mangrok:request-auth-token",{detail:{resolve:finish}}));setTimeout(()=>finish(""),700)})}
