import { STICKER_CATALOG, STICKER_CATEGORIES, searchStickers, createStickerLayer, normalizeStickerLayers, getSticker, stickerDataUri } from "./sticker-library.js";

const STORAGE_KEY = "mangrok.print.sticker.layers.v1";
const MAX_LAYERS = 48;
const state = { query: "", category: "All", layers: loadLayers(), selectedLayerId: null };

ready(init);
function ready(callback){if(document.readyState === "loading") document.addEventListener("DOMContentLoaded",callback,{once:true});else callback();}
function init(){
  const view=document.querySelector("#view-print"); if(!view || document.querySelector("#mangrok-sticker-studio")) return;
  hideLegacyDecorationControls(view);
  const studio=document.createElement("section"); studio.id="mangrok-sticker-studio"; studio.className="panel mangrok-sticker-studio";
  studio.innerHTML=`
    <header class="sticker-studio__header"><div><p class="eyebrow">Mangrok book atelier</p><h3>Sticker & label studio</h3><p>Build a printable scrapbook layer with original culinary artwork and editable recipe labels.</p></div><strong id="sticker-layer-count">0 / ${MAX_LAYERS}</strong></header>
    <div class="sticker-studio__workspace">
      <section class="sticker-browser" aria-label="Sticker library"><div class="sticker-browser__filters"><label>Search<input id="sticker-search" type="search" placeholder="Search labels, botanicals, kitchen tools"></label><label>Collection<select id="sticker-category">${STICKER_CATEGORIES.map(value=>`<option>${escapeHtml(value)}</option>`).join("")}</select></label></div><div id="sticker-grid" class="sticker-grid"></div></section>
      <section class="sticker-canvas-panel" aria-label="Sticker layout"><div class="sticker-canvas-toolbar"><label>Page<select id="sticker-target-page"><option value="cover">Cover</option><option value="all">Every page</option><option value="recipe">Recipe pages</option></select></label><button type="button" class="mini-button" id="sticker-clear">Clear layout</button><button type="button" class="mini-button" id="sticker-proof">Print sticker proof</button></div><div id="sticker-mini-canvas" class="sticker-mini-canvas" aria-label="Book decoration preview"><div><p>Mangrok</p><h4>My Recipe Book</h4><small>Cook · taste · adjust · love</small></div><div class="sticker-mini-canvas__layers"></div></div><div id="sticker-layer-editor" class="sticker-layer-editor"></div></section>
    </div><input id="print-illustrations" name="print-illustrations" type="hidden" value="[]">`;
  const anchor=view.querySelector(".print-preview")||view.querySelector(".print-layout")||view.lastElementChild; anchor?.insertAdjacentElement("beforebegin",studio)||view.append(studio);
  bind(studio); render(); observePrintPreview(view);
}
function hideLegacyDecorationControls(view){for(const node of view.querySelectorAll(".illustration-studio,.print-illustrations,[data-print-illustration-studio]")) node.hidden=true;view.querySelector("#print-illustrations")?.remove();}
function bind(root){
  root.querySelector("#sticker-search").addEventListener("input",event=>{state.query=event.target.value;renderLibrary();});
  root.querySelector("#sticker-category").addEventListener("change",event=>{state.category=event.target.value;renderLibrary();});
  root.querySelector("#sticker-target-page").addEventListener("change",event=>{const layer=selectedLayer();if(layer)replaceLayer({...layer,page:event.target.value});});
  root.querySelector("#sticker-grid").addEventListener("click",event=>{const button=event.target.closest("[data-sticker-id]");if(!button||state.layers.length>=MAX_LAYERS)return;const offset=state.layers.length%8;const layer=createStickerLayer(button.dataset.stickerId,{x:20+offset*8,y:20+(offset%4)*14});state.layers=[...state.layers,layer];state.selectedLayerId=layer.id;persistAndRender();});
  root.querySelector("#sticker-mini-canvas").addEventListener("click",event=>{const layer=event.target.closest("[data-layer-id]");if(!layer)return;state.selectedLayerId=layer.dataset.layerId;renderCanvas();renderEditor();});
  root.querySelector("#sticker-layer-editor").addEventListener("input",updateSelectedFromControls);root.querySelector("#sticker-layer-editor").addEventListener("change",updateSelectedFromControls);
  root.querySelector("#sticker-layer-editor").addEventListener("click",event=>{if(event.target.closest("[data-delete-layer]")){state.layers=state.layers.filter(layer=>layer.id!==state.selectedLayerId);state.selectedLayerId=state.layers.at(-1)?.id||null;persistAndRender();}if(event.target.closest("[data-duplicate-layer]")){const layer=selectedLayer();if(!layer||state.layers.length>=MAX_LAYERS)return;const duplicate=createStickerLayer(layer.stickerId,{...layer,id:undefined,x:Math.min(94,layer.x+6),y:Math.min(94,layer.y+6)});state.layers=[...state.layers,duplicate];state.selectedLayerId=duplicate.id;persistAndRender();}if(event.target.closest("[data-layer-back]"))moveLayer(-1);if(event.target.closest("[data-layer-forward]"))moveLayer(1);});
  root.querySelector("#sticker-clear").addEventListener("click",()=>{if(!state.layers.length||!confirm("Remove every sticker and label from this book layout?"))return;state.layers=[];state.selectedLayerId=null;persistAndRender();});
  root.querySelector("#sticker-proof").addEventListener("click",printStickerProof);
}
function render(){renderLibrary();renderCanvas();renderEditor();syncHiddenInput();renderIntoBookPreview();}
function renderLibrary(){const grid=document.querySelector("#sticker-grid");if(!grid)return;const matches=searchStickers({query:state.query,category:state.category});grid.innerHTML=matches.map(sticker=>`<button type="button" data-sticker-id="${escapeAttribute(sticker.id)}" ${state.layers.length>=MAX_LAYERS?"disabled":""}><img src="${stickerDataUri(sticker)}" alt=""><span>${escapeHtml(sticker.name)}</span><small>${escapeHtml(sticker.category)}</small></button>`).join("")||`<p class="empty-state">No stickers match this search.</p>`;const count=document.querySelector("#sticker-layer-count");if(count)count.textContent=`${state.layers.length} / ${MAX_LAYERS}`;}
function renderCanvas(){const canvas=document.querySelector("#sticker-mini-canvas .sticker-mini-canvas__layers");if(!canvas)return;canvas.innerHTML=state.layers.filter(layer=>layer.page==="cover"||layer.page==="all").map((layer,index)=>`<button type="button" class="sticker-layer-object ${layer.id===state.selectedLayerId?"selected":""}" data-layer-id="${escapeAttribute(layer.id)}" style="left:${layer.x}%;top:${layer.y}%;opacity:${layer.opacity};transform:translate(-50%,-50%) rotate(${layer.rotation}deg) scale(${layer.scale});z-index:${index+2}"><img src="${stickerDataUri(layer.stickerId,{text:layer.text})}" alt="${escapeAttribute(getSticker(layer.stickerId)?.name||"Sticker")}"></button>`).join("");}
function renderEditor(){const root=document.querySelector("#sticker-layer-editor");if(!root)return;const layer=selectedLayer();if(!layer){root.innerHTML=`<p>Select a sticker on the book to resize, rotate, move, or edit its label.</p>`;return;}const sticker=getSticker(layer.stickerId);document.querySelector("#sticker-target-page").value=layer.page;root.innerHTML=`<header><div><small>Selected layer</small><h4>${escapeHtml(sticker?.name||"Sticker")}</h4></div><div><button type="button" class="mini-button" data-duplicate-layer>Duplicate</button><button type="button" class="mini-button danger" data-delete-layer>Delete</button></div></header>${sticker?.editableText?`<label class="wide">Label text<input data-layer-field="text" maxlength="42" value="${escapeAttribute(layer.text)}"></label>`:""}<div class="sticker-control-grid"><label>Horizontal <input data-layer-field="x" type="range" min="3" max="97" step="1" value="${layer.x}"><output>${Math.round(layer.x)}%</output></label><label>Vertical <input data-layer-field="y" type="range" min="3" max="97" step="1" value="${layer.y}"><output>${Math.round(layer.y)}%</output></label><label>Size <input data-layer-field="scale" type="range" min="0.35" max="2.5" step="0.05" value="${layer.scale}"><output>${Math.round(layer.scale*100)}%</output></label><label>Rotate <input data-layer-field="rotation" type="range" min="-180" max="180" step="1" value="${layer.rotation}"><output>${Math.round(layer.rotation)}°</output></label><label>Opacity <input data-layer-field="opacity" type="range" min="0.15" max="1" step="0.05" value="${layer.opacity}"><output>${Math.round(layer.opacity*100)}%</output></label></div><footer><button type="button" class="mini-button" data-layer-back>Send backward</button><button type="button" class="mini-button" data-layer-forward>Bring forward</button></footer>`;}
function updateSelectedFromControls(event){const field=event.target.dataset.layerField;if(!field)return;const layer=selectedLayer();if(!layer)return;replaceLayer({...layer,[field]:field==="text"?event.target.value:Number(event.target.value)});}
function replaceLayer(value){const normalized=normalizeStickerLayers([value],1)[0];if(!normalized)return;state.layers=state.layers.map(layer=>layer.id===normalized.id?normalized:layer);persistAndRender(false);}
function moveLayer(delta){const index=state.layers.findIndex(layer=>layer.id===state.selectedLayerId),target=index+delta;if(index<0||target<0||target>=state.layers.length)return;const next=[...state.layers];[next[index],next[target]]=[next[target],next[index]];state.layers=next;persistAndRender();}
function persistAndRender(full=true){state.layers=[...normalizeStickerLayers(state.layers,MAX_LAYERS)];try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.layers));}catch{}if(full)render();else{renderCanvas();renderEditor();syncHiddenInput();renderIntoBookPreview();}}
function syncHiddenInput(){const input=document.querySelector("#print-illustrations");if(!input)return;input.value=JSON.stringify(state.layers);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));}
function observePrintPreview(view){new MutationObserver(()=>renderIntoBookPreview()).observe(view,{childList:true,subtree:true});}
function renderIntoBookPreview(){for(const target of document.querySelectorAll("#print-preview,.print-preview,[data-print-preview],.book-preview")){if(target.closest("#mangrok-sticker-studio"))continue;let overlay=target.querySelector(":scope > .mangrok-sticker-preview-overlay");if(!overlay){overlay=document.createElement("div");overlay.className="mangrok-sticker-preview-overlay";target.append(overlay);}overlay.innerHTML=state.layers.filter(layer=>layer.page==="cover"||layer.page==="all").map((layer,index)=>`<img src="${stickerDataUri(layer.stickerId,{text:layer.text})}" alt="" style="left:${layer.x}%;top:${layer.y}%;opacity:${layer.opacity};transform:translate(-50%,-50%) rotate(${layer.rotation}deg) scale(${layer.scale});z-index:${index+2}">`).join("");}}
function printStickerProof(){const layers=state.layers.filter(layer=>layer.page==="cover"||layer.page==="all"),popup=window.open("","_blank","noopener,noreferrer");if(!popup)return;const art=layers.map((layer,index)=>`<img src="${stickerDataUri(layer.stickerId,{text:layer.text})}" alt="" style="position:absolute;left:${layer.x}%;top:${layer.y}%;width:140px;opacity:${layer.opacity};transform:translate(-50%,-50%) rotate(${layer.rotation}deg) scale(${layer.scale});z-index:${index+2}">`).join("");popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Mangrok sticker proof</title><style>@page{size:8.5in 11in;margin:.25in}*{box-sizing:border-box}body{margin:0;font-family:Georgia,serif;background:#eee}.page{position:relative;width:8in;height:10.5in;margin:0 auto;overflow:hidden;background:linear-gradient(145deg,#4a1537,#24101f);color:#fff7e7;border:14px double #d49a28;display:grid;place-items:center;text-align:center}.page h1{font-size:62px;margin:0}.page p{letter-spacing:.3em;text-transform:uppercase}.page:after{content:"Sticker proof — verify bleed, safe area, and print resolution before ordering";position:absolute;bottom:16px;font:12px Arial;color:#efd9a5}@media print{body{background:#fff}}</style></head><body><section class="page"><div><h1>Mangrok</h1><p>My Recipe Book</p></div>${art}</section><script>addEventListener('load',()=>setTimeout(()=>print(),250))<\/script></body></html>`);popup.document.close();}
function selectedLayer(){return state.layers.find(layer=>layer.id===state.selectedLayerId)||null;}
function loadLayers(){try{return[...normalizeStickerLayers(JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]"),MAX_LAYERS)];}catch{return[];}}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);}
function escapeAttribute(value){return escapeHtml(value).replace(/`/g,"&#96;");}
export const STICKER_STUDIO_CONFIG=Object.freeze({STORAGE_KEY,MAX_LAYERS,stickerCount:STICKER_CATALOG.length});
